#importamos la imagen base de python 3.12 slim
FROM python:3.12-slim 

#Crear carpeta de trabajo
WORKDIR /app

#Copiar requerimientos
COPY requirements.txt .

#Instalar requirimientos
RUN pip install --no-cache-dir -r requirements.txt

#Copiar archivo del API
COPY ./app ./app

#Exponer el puerto
EXPOSE 5000

#Comando para ejecutar FastAPI
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]